<?php

/**
 * @file
 * Used to convert node of type page to json.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Config\ConfigFactoryInterface;

/**
 * Implements hook_form_alter().
 */
function node_page_json_form_alter(&$form, $form_state, $form_id) {
	if ($form_id == 'system_site_information_settings') {
		$site_api_key = \Drupal::configFactory()->getEditable('system.site')->get('siteapikey') ?: 'No API Key yet';
		$form['site_api_configuration'] = [
			  '#type' => 'details',
			  '#title' => t('Site api configuration'),
			  '#open' => TRUE,
		];
		$form['site_api_configuration']['site_api_key'] = [
			  '#type' => 'textfield',
			  '#title' => t('Site api key'),
			  '#default_value' => $site_api_key,
			  '#required' => TRUE,
		];
		$form['actions']['submit']['#value'] = "Update Configuration";
		$form['#submit'][] = 'save_api_key';
	}
}

//Submit handler to save api key.
function save_api_key(array &$form, FormStateInterface $form_state) {
	  \Drupal::configFactory()->getEditable('system.site')->set('siteapikey', $form_state->getValue('site_api_key'))->save();
	   $msg = 'Site API Key has been saved with the value ' . site_api_key;
	  drupal_set_message($msg);
}
